name: Docker CI

on:
  push:
    branches: [ "master", "development" ]
  pull_request:
    branches: [ "master" ]
env:
  DJANGO_SECRET_KEY: ${{ vars.DJANGO_SECRET_KEY }}
  DEBUG: ${{ vars.DEBUG }}
  DJANGO_ALLOWED_HOSTS: ${{ vars.DJANGO_ALLOWED_HOSTS }}
  DATABASE_ENGINE: ${{ vars.DATABASE_ENGINE }}
  DATABASE_NAME: ${{ vars.DATABASE_NAME }}
  DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
  DATABASE_PASSWORD: ${{ vars.DATABASE_PASSWORD }}
  DATABASE_HOST: ${{ vars.DATABASE_HOST }}
  DATABASE_PORT: ${{ vars.DATABASE_PORT }}

jobs:
  
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker compose up -d 
    - name: Test
      run: curl -s --retry 10 --retry-connrefused http://localhost
